apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-config
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"
    admin_variables={
        admin_credentials="admin:admin_password" # ProxySQL 관리자 계정
        mysql_ifaces="0.0.0.0:6032"
    }
    mysql_variables={
        threads=4
        max_connections=2048
        default_query_delay=0
        interfaces="0.0.0.0:6033" # 앱이 접속할 포트
    }
    # 1. DB 서버 등록 (Multi-AZ 엔드포인트)
    mysql_servers = (
        { address="://ian-mysql-cluster-rds.cluster-chkq2qcy82ik.ap-south-1.rds.amazonaws.com", port=3306, hostgroup=10, status="ONLINE" }, # Writer
        { address="://ian-mysql-cluster-rds.cluster-ro-chkq2qcy82ik.ap-south-1.rds.amazonaws.com", port=3306, hostgroup=20, status="ONLINE" }  # Reader
    )
    # 2. 읽기/쓰기 분리 규칙 (Query Rules)
    mysql_query_rules = (
        { rule_id=1, active=1, match_digest="^SELECT.*FOR UPDATE$", destination_hostgroup=10, apply=1 }, # 쓰기용 SELECT
        { rule_id=2, active=1, match_digest="^SELECT", destination_hostgroup=20, apply=1 },            # 일반 SELECT (Reader로)
        { rule_id=3, active=1, match_digest=".*", destination_hostgroup=10, apply=1 }                  # 나머지는 Writer로
    )
    # 3. DB 접속 사용자 정보 (앱에서 사용하는 계정과 동일해야 함)
    mysql_users = (
        # { username="db_user", password="db_password", default_hostgroup=10, active=1 }
        { username="ian", password="ian1234!", default_hostgroup=10, active=1 }
    )

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      affinity: # 노드 분산 배치
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["proxysql"]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: proxysql
        image: proxysql/proxysql:latest
        ports:
        - containerPort: 6033 # 서비스 포트
        - containerPort: 6032 # 관리 포트
        volumeMounts:
        - name: config
          mountPath: /etc/proxysql.cnf
          subPath: proxysql.cnf
      volumes:
      - name: config
        configMap:
          name: proxysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: proxysql-svc
spec:
  selector:
    app: proxysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 6033
